"""Recreate DB schema

Revision ID: 38db3047e5ec
Revises: 
Create Date: 2025-02-01 18:57:25.348009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38db3047e5ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('personas_base_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('additional_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('quote_summarized', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_uploaded_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('activity_01', sa.Text(), nullable=True),
    sa.Column('activity_02', sa.Text(), nullable=True),
    sa.Column('activity_03', sa.Text(), nullable=True),
    sa.Column('activity_04', sa.Text(), nullable=True),
    sa.Column('activity_05', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_digital_use',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('desktop_use', sa.Text(), nullable=False),
    sa.Column('mobile_use', sa.Text(), nullable=False),
    sa.Column('social_media_use', sa.Text(), nullable=False),
    sa.Column('computer_literacy', sa.Text(), nullable=False),
    sa.Column('frequently_used_tools_and_apps', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_frustrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('frustration_01', sa.Text(), nullable=False),
    sa.Column('frustration_02', sa.Text(), nullable=True),
    sa.Column('frustration_03', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('goal_01', sa.Text(), nullable=False),
    sa.Column('goal_02', sa.Text(), nullable=True),
    sa.Column('goal_03', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_motivations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('motivation_01', sa.Text(), nullable=False),
    sa.Column('motivation_02', sa.Text(), nullable=True),
    sa.Column('motivation_03', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('quote_01', sa.Text(), nullable=True),
    sa.Column('quote_02', sa.Text(), nullable=True),
    sa.Column('quote_03', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas_base_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_quotes')
    op.drop_table('persona_motivations')
    op.drop_table('persona_goals')
    op.drop_table('persona_frustrations')
    op.drop_table('persona_digital_use')
    op.drop_table('persona_activities')
    op.drop_table('user_uploaded_data')
    op.drop_table('personas_base_data')
    op.drop_table('users')
    # ### end Alembic commands ###
