"""Initial migration

Revision ID: 487c677a8107
Revises: 
Create Date: 2024-12-06 10:46:07.385855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487c677a8107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    with op.batch_alter_table('user_uploaded_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'personas_base_data', ['persona_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_uploaded_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('persona_id')

    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
