"""Add persona_id to user_uploaded_data

Revision ID: a5c0cfa97f80
Revises: 38db3047e5ec
Create Date: 2025-02-02 12:24:24.190762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c0cfa97f80'
down_revision = '38db3047e5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_uploaded_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_uploaded_data_persona',  # ✅ Explicitly named foreign key
            'personas_base_data',
            ['persona_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_uploaded_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_uploaded_data_persona', type_='foreignkey')  # ✅ Corrected constraint removal
        batch_op.drop_column('persona_id')

    # ### end Alembic commands ###
